services:
  mongo:
    image: mongo:8.0.4
    container_name: mongo
    restart: always
    environment:
      MONGO_PORT: 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
